version: 2.1
orbs: 
  slack: circleci/slack@4.6.2
jobs:
  build:
    working_directory: ~/app
    docker:
      - image: circleci/ruby:3.0.0-node-browsers
        environment:
          - RAILS_ENV: test
          - MYSQL_DATABASE: 'ci_test'
          - MYSQL_USER: 'root'
          - MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
          - MYSQL_PASSWORD: ''
          - MYSQL_HOST: 127.0.0.1
          - MYSQL_PORT: 3306
      - image: circleci/mysql:5.7.33
          

    steps:
      - checkout
      - run: bundle install
      - run: mv config/database.yml.ci config/database.yml
      - run: cat config/database.yml
      - run: rails db:create
      - run: rails db:migrate
      - run: yarn install
      - run: rails webpacker:compile
      - run: 
          name: Rubocop
          command: bundle exec rubocop
      - run:
          name: Rspec
          command: rspec
  
  notify:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - slack/notify:
          custom: |
            {
              "blocks": [
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "plain_text",
                      "text": "*This is a text notification*",
                      "emoji": true
                    }
                  ]
                }
              ]
            }
          event: always
workflows:
  version: 2
  send-notification:
    jobs:
      - build
      - notify

      
        